apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-{{ .Release.Name }}
  labels:
    app: dummy-{{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  description: "dump"